package ro.project;

public class Constants {

	private Constants() {}
	public static final String ACCESS_TOKEN_PATH  = "C:/Tomcat/apache-tomcat-7.0.59/webapps/accessToken.txt";
	
	public static final String MOZILLA_USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64; rv:32.0) Gecko/20100101 Firefox/32.0";
	public static final String BOXY_PADDING_BIG = "boxyPaddingBig";
	public static final String BQ_QUOTE_LINK = "bqQuoteLink";
	public static final String HREF_A = "a";
	public static final String BQ_AUT = "bq-aut";
	public static final String NAV = "nav";
	public static final String BRAINIQUOTE_URL = "http://www.brainyquote.com/";
	public static final String PERSDEV_URL = "http://persdev-q.com/";
	public static final String HREF = "href";
	public static final String QUOTES_FILE = "quotes/";
	public static final String HTTP = "http";
	public static final String WWW = "www";
	public static final String HTML = "html";
	public static final String TAG_ARTICLE = "article";
	public static final String TAG_P = "p";
	public static final String TAG_LAQUO = "&laquo;";
	public static final String TAG_RAQUO = "&raquo;";
	public static final String TAG_EM = "<em>";
	public static final String TAG_EM_END = "</em>";
	public static final String TAG_STRONG  = "<strong>";
	public static final String TAG_STRONG_END = "</strong";
	public static final String TAG_P_END = "</p>";
	public static final String TAG_BR = "<br />";
	public static final String MOZILLA = "Mozilla/5.0";
	public static final String BUFFERAPP_CREATE ="https://api.bufferapp.com/1/updates/create.json?access_token=";
	public static final String POST  = "POST";
	public static final String GET  = "GET";
	public static final String USER_AGENT = "User-Agent";
	public static final String DATE_FORMAT = "yyyy-MM-dd HH:mm:ssz";
	public static final String BUFFERAPP_PROFILES = "https://api.bufferapp.com/1/profiles/";
	public static final String ACCESS_TOKEN_PARAM = "&access_token=";
	public static final String BUFFERAPP_UPDATES = "https://api.bufferapp.com/1/updates/";
	public static final String FORMATED_SERVICE = "formatted_service";
	public static final String BUFFERAPP_PROFILES_JSON = "https://api.bufferapp.com/1/profiles.json";
	public static final String FACEBOOK = "facebook";
	public static final String GOOGLE = "google+page";
	public static final String LINKEDIN = "linkeding";
	public static final String TWITTER = "twitter";
	public static final String ACCESS_TOKEN = "accessToken";
	public static final String BY_DATE = "byDate";
	public static final String BY_AUTHOR = "byAuthor";
	public static final String BY_QUOTE = "byQuote";
	public static final String TOTAL = "total";
	public static final int QUOTE_HISTORY_LIMIT = 1000;
	public static final String PROFILE_SERVICE = "profile_service";
	public static final String UPDATES = "updates";
	public static final String DUE_AT = "due_at";
	public static final String DUE_TIME = "due_time";
	public static final String TEXT = "text";
	public static final String PARSER_TXT = "parser.txt";
	public static final int UPDATES_PER_PAGE = 20;
	public static final String RADIOS = "radios";
	public static final String WEBSITE = "website";
	public static final String PATH = "path";
	public static final String TYPE = "type";
	public static final String ORDER = "order";
	public static final String ORDER_ASCENDING = "ascending";
	public static final String PAGE = "page";
	public static final String AUTH = "auth";
	public static final String QUOTES_LIST = "quotesList";
	public static final String NO_OF_PAGES = "noOfPages";
	public static final String CURRENT_PAGE = "currentPage";
	public static final String LAST_TYPE = "lastType";
	public static final String PATH_2 = "path2";
	public static final String WHERE = "where";
	public static final String YEAR_DROP_DOWN = "yeardropdown";
	public static final String MONTH_DROP_DOWN = "monthdropdown";
	public static final String DAY_DROP_DOWN = "daydropdown";
	public static final String HOUR_DROP_DOWN = "hourdropdown";
	public static final String MINUTE_DROP_DOWN = "minutedropdown";
	public static final String GMT_DROP_DOWN = "gmtdropdown";
}
